### ISSUE TITLE
JAR download for JBLAS 1.2.5

### ISSUE THREAD

**Issue by vrdn-23** [jblas-project/jblas#121]
Hi,

Kudos on maintaining and creating such an amazing library. I was wondering if it would be possible to be provided with the download links for the latest 1.2.5 version jar?

TIA

**Comment by vrdn-23** [comment]
Oops. Sorry about that. Just saw that that it's available on maven central. 

https://mvnrepository.com/artifact/org.jblas/jblas/1.2.5

**Comment by mikiobraun** [comment]
No worries and thanks, Vinay!

**Comment by vrdn-23** [comment]
Hey @mikiobraun ,

Sorry for the quick question, but we're facing this issue when trying to run the jblas jar on one of our CentOS servers. 
```code


-bash-4.2$ java -jar jblas-1.2.5.jar 
-- org.jblas INFO jblas version is 1.2.4
Simple benchmark for jblas

Running sanity benchmarks.

checking vector addition... ok
-- org.jblas CONFIG BLAS native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH).
-- org.jblas CONFIG Loading libquadmath-0.so from /lib/static/Linux/amd64/, copying to libquadmath-0.so.
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/jblas5367314395687030851/libquadmath-0.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/jblas5367314395687030851/libquadmath-0.so).

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jblas.NativeBlas.dgemm(CCIIID[DII[DIID[DII)V
	at org.jblas.NativeBlas.dgemm(Native Method)
	at org.jblas.SimpleBlas.gemm(SimpleBlas.java:247)
	at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1793)
	at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3166)
	at org.jblas.util.SanityChecks.checkMatrixMultiplication(SanityChecks.java:91)
	at org.jblas.util.SanityChecks.main(SanityChecks.java:182)
	at org.jblas.benchmark.Main.main(Main.java:114)
-- org.jblas INFO Deleting /tmp/jblas5367314395687030851/libquadmath-0.so
-- org.jblas INFO Deleting /tmp/jblas5367314395687030851

```

Does this imply that we need to install libgfortran5 for jblas to run? This is a server where we have limited access to and need to raise a request to update any software so I want to make sure I raise the request for the right library the first time. 

Please let me know if you require any other information.

**Comment by mikiobraun** [comment]
Which version of CentOS are you running?

**Comment by vrdn-23** [comment]
```
-bash-4.2$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
```

**Comment by mikiobraun** [comment]
Okay, let me have a deeper look. For now, if 1.2.4 still works for you, I recommend you stick with that version, there were no major functionality changes in 1.2.5.

**Comment by vrdn-23** [comment]
So this issue is reproducible for me on 1.2.2. and 1.2.3.

**Comment by vrdn-23** [comment]
```
-bash-4.2$ java -jar jblas-1.2.3.jar 
-- org.jblas INFO jblas version is 1.2.3
Simple benchmark for jblas

Running sanity benchmarks.

checking vector addition... ok
-- org.jblas CONFIG BLAS native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH).
-- org.jblas CONFIG ArchFlavor native library not found in path. Copying native library libjblas_arch_flavor from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH).
-- org.jblas CONFIG Loading libjblas_arch_flavor.so from /lib/static/Linux/amd64/, copying to libjblas_arch_flavor.so.
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/jblas12547425626028564858libjblas_arch_flavor.so: libgfortran.so.3: cannot open shared object file: No such file or directory.

On Linux 64bit, you need additional support libraries.
You need to install libgfortran3.

For example for debian or Ubuntu, type "sudo apt-get install libgfortran3"

For more information, see https://github.com/mikiobraun/jblas/wiki/Missing-Libraries
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jblas.NativeBlas.dgemm(CCIIID[DII[DIID[DII)V
	at org.jblas.NativeBlas.dgemm(Native Method)
	at org.jblas.SimpleBlas.gemm(SimpleBlas.java:251)
	at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1697)
	at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3054)
	at org.jblas.util.SanityChecks.checkMatrixMultiplication(SanityChecks.java:91)
	at org.jblas.util.SanityChecks.main(SanityChecks.java:182)
	at org.jblas.benchmark.Main.main(Main.java:114)
```

```
-bash-4.2$ java -jar jblas-1.2.2.jar 
Simple benchmark for jblas

Running sanity benchmarks.

checking vector addition... ok
-- org.jblas CONFIG BLAS native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH).
-- org.jblas CONFIG ArchFlavor native library not found in path. Copying native library libjblas_arch_flavor from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH).
-- org.jblas CONFIG Loading libjblas_arch_flavor.so from /lib/static/Linux/amd64/, copying to libjblas_arch_flavor.so.
-- org.jblas CONFIG Loading libjblas.so from /lib/static/Linux/amd64/sse3/, copying to libjblas.so.
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/jblas7141347152068656838libjblas.so: libgfortran.so.3: cannot open shared object file: No such file or directory.

On Linux 64bit, you need additional support libraries.
You need to install libgfortran3.

For example for debian or Ubuntu, type "sudo apt-get install libgfortran3"

For more information, see https://github.com/mikiobraun/jblas/wiki/Missing-Libraries
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.jblas.NativeBlas.dgemm(CCIIID[DII[DIID[DII)V
	at org.jblas.NativeBlas.dgemm(Native Method)
	at org.jblas.SimpleBlas.gemm(SimpleBlas.java:251)
	at org.jblas.DoubleMatrix.mmuli(DoubleMatrix.java:1696)
	at org.jblas.DoubleMatrix.mmul(DoubleMatrix.java:3027)
	at org.jblas.util.SanityChecks.checkMatrixMultiplication(SanityChecks.java:91)
	at org.jblas.util.SanityChecks.main(SanityChecks.java:182)
	at org.jblas.benchmark.Main.main(Main.java:109)

```
